START:
	DIS I
	STRT T
	MOV R7, #0
	EN TCNTI
	JMP PGM_START
TRUPT:
	INC R7
	RETR
PGM_START:
	CALL UART_INIT
LOOP:
	MOV A, R7
	ADD A, #1
	JNC LOOP
TIMER_EVENT:
	MOV A, #116
	CALL UART_WRITE
	MOV A, #101
	CALL UART_WRITE
	MOV A, #115
	CALL UART_WRITE
	MOV A, #116
	CALL UART_WRITE
	MOV A, 10
	CALL UART_WRITE
	MOV A, 13
	CALL UART_WRITE
WAIT_FOR_COUNT:
	MOV A, R7
	ADD A, #1
	JC WAIT_FOR_COUNT
	JMP LOOP

UART_WRITE:
	ANL P2,#249
	OUTL BUS,A
	ORL P2,#2
UART_WRITE_DELAY_LOOP:
	IN A,P2
	ANL A,#8
	JZ UART_WRITE_DELAY_LOOP
	RET

	;Connection of P8251 to microcontroller:
	;DB - DB7 = D0 - D7
	;P20 = RESET
	;P21 = CS (may be omitted, and CS pulled to GND on P8251, if only device on bus)
	;P22 = C/D
	;P23 = TxEMPTY
UART_INIT:
	MOV A,#0b00001111
	OUTL P2,A
	CALL DELAY
	ANL P2,#254
	CALL DELAY
	ANL P2,#253
	MOV A,#0b01001110 ; Mode word: 1 stop bit, no parity, 8-bit, 16X baud rate divisor
	OUTL BUS,A
	MOV A,#0b00110011 ; Command word: Enable TX, but not RX, reset error flags
	OUTL BUS,A
	ORL P2,#2
	RET

DELAY:
	MOV A,#0xFF
DELAY_LOOP:
	ADD A,#0xFF
	NOP
	NOP
	NOP
	NOP
	NOP
	JNZ DELAY_LOOP
	RETR
